baseURL = "https://tedmdelacruz.github.io"
languageCode = "en-us"
title = "tedmdelacruz"
theme = "tale"
[params]
  subtitle = "Software developer and cybersecurity researcher based in Manila, PH"
  css = ["styles.css"]