baseURL = "https://tedmdelacruz.github.io"
languageCode = "en-us"
googleAnalytics = "G-59X131RVLB"
title = "tedmdelacruz"
theme = "tale"
[params]
  subtitle = "Software developer and cybersecurity researcher based in Manila, PH"
  css = ["styles.css"]
  author = { name = "Ted Mathew dela Cruz" }